package Pack;

public class Exception2 
{
	 
    public static void main(String[] args) 
    {
        try 
        { 
            return; 
        } 
        finally 
        {
            System.out.println( "Finally" ); 
        }    } 

}
